backend:
  name: github
  repo: peroin/webkatalog
  branch: main
  base_url: https://ailabss.milliarsatu4.workers.dev
  auth_endpoint: /auth

# Tambahkan ini agar CMS tahu alamat aslinya
site_url: https://ailabss.pages.dev
display_url: https://ailabss.pages.dev

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Artikel Weekly Report"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul SEO", name: "title", widget: "string"}
      - {label: "Tanggal Publish", name: "date", widget: "datetime"}
      - {label: "Kategori", name: "category", widget: "select", options: ["Automation", "Neural", "Local AI"]}
      - {label: "Ringkasan (Untuk Google)", name: "summary", widget: "text"}
      - {label: "Isi Artikel", name: "body", widget: "markdown"}
